name: Publish to Comfy registry
on:
  workflow_dispatch:
  pull_request:

jobs:
  publish-node:
    name: Publish Custom Node to registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Include submodule files
        run: |
          # Remove submodule metadata carefully without deleting files
          git rm --cached repositories/ultimate_sd_upscale
          rm -rf repositories/ultimate_sd_upscale/.git
          # Re-add files as regular
          git add repositories/ultimate_sd_upscale
  
          ls -la repositories/ultimate_sd_upscale     
          # commit the changes so that the files become tracked
          # git config --global user.email "action@github.com"
          # git config --global user.name "GitHub Action"
          # git commit -m "Include submodule files for publish" || true

      - name: Listing Git Files
        run: |
          git ls-files     
